name: Bounty
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
main: Infernus101\Main
version: 2.0.0-beta1
author: Zeao
description: Bounty plugin for Faction servers.
commands:
  bounty:
    description: "Bounty help"
