name: Bounty
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
main: Infernus101\Main
version: 1.0.0
author: VMPE Development Team
description: Bounty plugin for Faction servers.
commands:
  bounty:
    description: "Bounty help"
